name: GitHub Actions to Dockerhub
run-name: ${{ github.actor }} test GitHub Actions to upload docker image 🚀
on: [push]
jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: build and tag image
      run: |
        docker build -t m1lk/github-action:v1 -f Dockerfile .
    
    - name: push to dockerhub
      run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_SECRET}} && docker push m1lk/github-action:v1